Change homepage
agile-france/2016 pull request #11
Opened 2017-01-24 06:41 UTC by Frederic-ANDRE

Delete schedule and financial links

2017-01-24 08:08 UTC, MattiSG requested changes
Il faudrait probablement également réordonner les différents blocs, comme documenté dans le README : https://github.com/agile-france/site-dessins/commit/2e306601ca23ffe07893095dc2a1f5479140be5d.

2017-01-24 08:08 UTC, MattiSG commented on app/assets/index.html
> +				<time datetime="2017-06-17" class="dtend">17</time>
Il n'y a pas que l'année qui a changé ! Les jours aussi sont décalés !

2017-01-24 08:08 UTC, MattiSG commented on app/assets/index.html
>  		<section id="ticket">
La billetterie n'est pas encore ouverte.

2017-01-25 22:35 UTC, Frederic-ANDRE commented
J'ai changé les date et supprimer la section billetterie.

2017-01-26 07:41 UTC, MattiSG approved these changes

2017-01-26 07:47 UTC, merged